import 'package:qayd/data/database/migrations/schema_migration.dart';
import 'package:sqflite_sqlcipher/sqflite.dart';

/// Schema v30: Per-attachment AES key storage.
///
/// Each attachment blob is encrypted with a **unique** AES-256 key generated
/// by [VoucherKeyService]. The plaintext key is stored here (the DB itself is
/// encrypted by SQLCipher) so that:
///   1. The sender can embed the key inside the E2EE sync payload.
///   2. The receiver stores it here after decrypting the payload.
///   3. [AttachmentStorageService.decrypt] uses it to decrypt the blob.
///   4. The backup ZIP preserves encrypted blobs; the key survives in the DB.
final class Migration030AttachmentKey implements SchemaMigration {
  @override
  int get version => 30;

  @override
  Future<void> up(Database db) async {
    // NULL = attachment encrypted with the legacy device-wide key (pre-v30).
    // Non-null = per-voucher key (hex) generated by VoucherKeyService.
    await db.execute(
      'ALTER TABLE attachments ADD COLUMN attachment_key_hex TEXT',
    );
  }
}
