import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:crypto/crypto.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path/path.dart' as p;
import 'package:qayd/data/database/database_encryption_key_provider.dart';
import 'package:qayd/data/encryption/file_encryptor.dart';
import 'package:qayd/data/encryption/voucher_key_service.dart';
import 'package:qayd/data/file_system/backup_file_manager.dart';
import 'package:qayd/domain/entities/voucher_attachment.dart';
import 'package:qayd/domain/value_objects/attachment_id.dart';
import 'package:qayd/domain/value_objects/attachment_source_type.dart';
import 'package:qayd/domain/value_objects/voucher_id.dart';
import 'package:qayd/presentation/l10n/app_strings.dart';
import 'package:uuid/uuid.dart';

/// Orchestrates secure storage of voucher images.
///
/// ### Encryption strategy (v30+)
/// Each attachment is encrypted with a **unique** AES-256 key generated by
/// [VoucherKeyService]. The IV is prepended to the ciphertext blob
/// (format: `IV (16 bytes) || ciphertext`), so each file is self-contained.
///
/// The per-attachment key is:
/// - Stored in the SQLCipher `attachments.attachment_key_hex` column.
/// - Embedded (hex) inside the E2EE sync payload so the counterparty can
///   decrypt images they download from the server.
/// - Preserved across backups because the DB is backed up alongside the blobs.
///
/// ### Legacy compatibility (pre-v30)
/// Attachments created before v30 have `attachment_key_hex = NULL` in the DB.
/// [decrypt] falls back to the device-wide key (SHA-256 of the DB passphrase)
/// so old images continue to work after a schema upgrade.
class AttachmentStorageService {
  AttachmentStorageService({
    required DatabaseEncryptionKeyProvider keyProvider,
    VoucherKeyService voucherKeyService = const VoucherKeyService(),
    BackupFileManager fileManager = const BackupFileManager(),
    FileEncryptor encryptor = const FileEncryptor(),
  })  : _keyProvider = keyProvider,
        _voucherKeyService = voucherKeyService,
        _fileManager = fileManager,
        _encryptor = encryptor;

  final DatabaseEncryptionKeyProvider _keyProvider;
  final VoucherKeyService _voucherKeyService;
  final BackupFileManager _fileManager;
  final FileEncryptor _encryptor;

  // ── Public API ─────────────────────────────────────────────────────────────

  /// Encrypts and stores a picked [source] image for the given [voucherId].
  ///
  /// Returns a [VoucherAttachment] whose [attachmentKeyHex] contains the
  /// unique per-file AES key. Persist this entity immediately; the key is
  /// the only way to decrypt this specific blob.
  Future<VoucherAttachment> store(
    XFile source,
    VoucherId voucherId,
  ) async {
    final imagesDir = await _fileManager.externalImagesDir();

    // Generate a unique AES key + IV for this specific attachment.
    final voucherKey = _voucherKeyService.generateVoucherKey(); // 32 bytes
    final keyHex = _bytesToHex(voucherKey);

    final id = const Uuid().v4();
    final ext = p.extension(source.path);
    final encryptedFileName = 'img_${id}_enc$ext';
    final destPath = p.join(imagesDir!.path, encryptedFileName);

    // Encrypt: VoucherKeyService.encryptBlob prepends a random IV (16 bytes).
    final plainBytes = Uint8List.fromList(await File(source.path).readAsBytes());
    final encryptedBytes = _voucherKeyService.encryptBlob(plainBytes, voucherKey);
    await File(destPath).writeAsBytes(encryptedBytes);

    // SHA-256 of the encrypted blob for server-side content-blind deduplication.
    final blobHash = sha256.convert(encryptedBytes).toString();
    final originalSize = await source.length();
    final mimeType = source.mimeType ?? _inferMimeType(ext);

    return VoucherAttachment(
      id: AttachmentId(id),
      voucherId: voucherId,
      fileName: source.name,
      storagePath: destPath,
      encryptedBlobHash: blobHash,
      mimeType: mimeType,
      byteSize: originalSize,
      sourceType: AttachmentSourceType.gallery,
      createdAt: DateTime.now(),
      // §5.E: unique per-attachment key — travels inside E2EE payload.
      attachmentKeyHex: keyHex,
    );
  }

  /// Decrypts an attachment into a raw byte buffer for display or export.
  ///
  /// ### Key resolution (in priority order):
  /// 1. [attachment.attachmentKeyHex] — per-attachment key (v30+, preferred).
  /// 2. [overrideKeyHex] — key extracted from an inbound E2EE payload (used
  ///    when the receiver has not yet written the key to the DB).
  /// 3. Legacy device-wide key — SHA-256(DB passphrase) for pre-v30 blobs.
  ///
  /// If [attachment.storagePath] no longer exists on disk (e.g. reinstall or
  /// new device after restore), a path-fallback searches the current
  /// [externalImagesDir] by filename.
  Future<Uint8List> decrypt(
    VoucherAttachment attachment, {
    String? overrideKeyHex,
  }) async {
    // Guard: blob not yet downloaded (inbound attachment pending sync).
    if (attachment.storagePath.isEmpty) {
      throw StateError(AppStrings.attachmentNotDownloadedYet);
    }

    final resolvedPath = await _resolvePath(attachment.storagePath);
    final encryptedBytes = Uint8List.fromList(
      await File(resolvedPath).readAsBytes(),
    );

    // Priority 1: per-attachment key stored in DB (v30+).
    final keyHex =
        attachment.attachmentKeyHex ?? overrideKeyHex;

    if (keyHex != null && keyHex.isNotEmpty) {
      // VoucherKeyService format: IV (16 bytes) || ciphertext
      final voucherKey = _hexToBytes(keyHex);
      return _voucherKeyService.decryptBlob(encryptedBytes, voucherKey);
    }

    // Priority 3: legacy device-wide key (pre-v30).
    final passphraseHex = await _keyProvider.obtainKey();
    final rawKey = _hexToBytes(passphraseHex);
    final aesKey = Uint8List.fromList(sha256.convert(rawKey).bytes);
    final aesIv = Uint8List.fromList(
        sha256.convert(utf8.encode('attachment_iv')).bytes.sublist(0, 16));

    return _encryptor.decrypt(encryptedBytes, aesKey, aesIv);
  }

  // ── Path resolution ────────────────────────────────────────────────────────

  /// Resolves [storedPath] to an existing file.
  ///
  /// Resolution order:
  /// 1. [storedPath] exactly (happy path — same device, same install).
  /// 2. `externalImagesDir/<filename>` (same device, reinstall).
  /// 3. Recursive search inside `externalImagesDir` by filename
  ///    (handles subdirectory nesting).
  /// 4. Returns [storedPath] unchanged → caller gets a descriptive
  ///    [FileSystemException] rather than a silent wrong-path error.
  Future<String> _resolvePath(String storedPath) async {
    if (storedPath.isNotEmpty && File(storedPath).existsSync()) return storedPath;

    final fileName = p.basename(storedPath);
    final imagesDir = await _fileManager.externalImagesDir();
    if (imagesDir != null && imagesDir.existsSync()) {
      // Fast: try the flat root first.
      final candidate = p.join(imagesDir.path, fileName);
      if (File(candidate).existsSync()) return candidate;

      // Slow: recursive walk for subdirectory nesting.
      for (final entity
          in imagesDir.listSync(recursive: true, followLinks: false)) {
        if (entity is File && p.basename(entity.path) == fileName) {
          return entity.path;
        }
      }
    }

    return storedPath; // will throw a descriptive FileSystemException downstream
  }


  // ── Helpers ────────────────────────────────────────────────────────────────


  Uint8List _hexToBytes(String hex) {
    final result = Uint8List(hex.length ~/ 2);
    for (var i = 0; i < result.length; i++) {
      result[i] = int.parse(hex.substring(i * 2, i * 2 + 2), radix: 16);
    }
    return result;
  }

  String _bytesToHex(Uint8List bytes) =>
      bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();

  String _inferMimeType(String ext) {
    return switch (ext.toLowerCase()) {
      '.jpg' || '.jpeg' => 'image/jpeg',
      '.png' => 'image/png',
      '.webp' => 'image/webp',
      _ => 'application/octet-stream',
    };
  }
}
