import 'package:qayd/data/models/country_model.dart';
import 'package:qayd/presentation/l10n/app_strings.dart';


List<CountryModel> countries = [
  CountryModel(
    id: "0",
    name: "Greece",
    status: "GR",
    arabicName: AppStrings.greece,
    countryCallingCode: "30",
  ),
  CountryModel(
    id: "1",
    name: "Afghanistan",
    status: "AF",
    arabicName: AppStrings.afghanistan,
    countryCallingCode: "93",
  ),
  CountryModel(
    id: "2",
    name: "Aland Islands",
    status: "AX",
    arabicName: AppStrings.landIslands,
    countryCallingCode: "358 18",
  ),
  CountryModel(
    id: "3",
    name: "Albania",
    status: "AL",
    arabicName: AppStrings.albania,
    countryCallingCode: "355",
  ),
  CountryModel(
    id: "4",
    name: "Algeria",
    status: "DZ",
    arabicName: AppStrings.algeria,
    countryCallingCode: "213",
  ),
  CountryModel(
    id: "5",
    name: "American Samoa",
    status: "AS",
    arabicName: AppStrings.americanSamoa,
    countryCallingCode: "1 684",
  ),
  CountryModel(
    id: "6",
    name: "Andorra",
    status: "AD",
    arabicName: AppStrings.andorra,
    countryCallingCode: "376",
  ),
  CountryModel(
    id: "7",
    name: "Angola",
    status: "AO",
    arabicName: AppStrings.angola,
    countryCallingCode: "244",
  ),
  CountryModel(
    id: "8",
    name: "Anguilla",
    status: "AI",
    arabicName: AppStrings.anguilla,
    countryCallingCode: "1 264",
  ),
  CountryModel(
    id: "9",
    name: "Antarctica",
    status: "AQ",
    arabicName: AppStrings.antarctica,
    countryCallingCode: "672 1",
  ),
  CountryModel(
    id: "10",
    name: "Antigua And Barbuda",
    status: "AG",
    arabicName: AppStrings.antiguaAndBarbuda,
    countryCallingCode: "1 268",
  ),
  CountryModel(
    id: "11",
    name: "Argentina",
    status: "AR",
    arabicName: AppStrings.argentina,
    countryCallingCode: "54",
  ),
  CountryModel(
    id: "12",
    name: "Armenia",
    status: "AM",
    arabicName: AppStrings.armenia,
    countryCallingCode: "374",
  ),
  CountryModel(
    id: "13",
    name: "Aruba",
    status: "AW",
    arabicName: AppStrings.aruba,
    countryCallingCode: "297",
  ),
  CountryModel(
    id: "14",
    name: "Australia",
    status: "AU",
    arabicName: AppStrings.australia,
    countryCallingCode: "61",
  ),
  CountryModel(
    id: "15",
    name: "Austria",
    status: "AT",
    arabicName: AppStrings.austria,
    countryCallingCode: "43",
  ),
  CountryModel(
    id: "16",
    name: "Azerbaijan",
    status: "AZ",
    arabicName: AppStrings.azerbaijan,
    countryCallingCode: "994",
  ),
  CountryModel(
    id: "17",
    name: "Bahamas",
    status: "BS",
    arabicName: AppStrings.bahamas,
    countryCallingCode: "1 242",
  ),
  CountryModel(
    id: "18",
    name: "Bahrain",
    status: "BH",
    arabicName: AppStrings.bahrain,
    countryCallingCode: "973",
  ),
  CountryModel(
    id: "19",
    name: "Bangladesh",
    status: "BD",
    arabicName: AppStrings.bangladesh,
    countryCallingCode: "880",
  ),
  CountryModel(
    id: "20",
    name: "Barbados",
    status: "BB",
    arabicName: AppStrings.barbados,
    countryCallingCode: "1 246",
  ),
  CountryModel(
    id: "21",
    name: "Belarus",
    status: "BY",
    arabicName: AppStrings.belarus,
    countryCallingCode: "375",
  ),
  CountryModel(
    id: "22",
    name: "Belgium",
    status: "BE",
    arabicName: AppStrings.belgium,
    countryCallingCode: "32",
  ),
  CountryModel(
    id: "23",
    name: "Belize",
    status: "BZ",
    arabicName: AppStrings.belize,
    countryCallingCode: "501",
  ),
  CountryModel(
    id: "24",
    name: "Benin",
    status: "BJ",
    arabicName: AppStrings.boys,
    countryCallingCode: "229",
  ),
  CountryModel(
    id: "25",
    name: "Bermuda",
    status: "BM",
    arabicName: AppStrings.bermuda,
    countryCallingCode: "1 441",
  ),
  CountryModel(
    id: "26",
    name: "Bhutan",
    status: "BT",
    arabicName: AppStrings.bhutan,
    countryCallingCode: "975",
  ),
  CountryModel(
    id: "27",
    name: "Bolivia",
    status: "BO",
    arabicName: AppStrings.bolivia,
    countryCallingCode: "591",
  ),
  CountryModel(
    id: "28",
    name: "Bosnia and Herzegovina",
    status: "BA",
    arabicName: AppStrings.bosniaAndHerzegovina,
    countryCallingCode: "387",
  ),
  CountryModel(
    id: "29",
    name: "Botswana",
    status: "BW",
    arabicName: AppStrings.botswana,
    countryCallingCode: "267",
  ),
  CountryModel(
    id: "30",
    name: "Bouvet Island",
    status: "BV",
    arabicName: AppStrings.beauvaisIsland,
    countryCallingCode: "47",
  ),
  CountryModel(
    id: "31",
    name: "Brazil",
    status: "BR",
    arabicName: AppStrings.brazil,
    countryCallingCode: "55",
  ),
  CountryModel(
    id: "32",
    name: "",
    status: "IO",
    arabicName: AppStrings.britishIndianOceanTerritory,
    countryCallingCode: "246",
  ),
  CountryModel(
    id: "33",
    name: "Brunei Darussalam",
    status: "BN",
    arabicName: AppStrings.bruneiDarussalam,
    countryCallingCode: "673",
  ),
  CountryModel(
    id: "34",
    name: "Bulgaria",
    status: "BG",
    arabicName: AppStrings.bulgaria,
    countryCallingCode: "359",
  ),
  CountryModel(
    id: "35",
    name: "Burkina Faso",
    status: "BF",
    arabicName: AppStrings.burkinaFaso,
    countryCallingCode: "226",
  ),
  CountryModel(
    id: "36",
    name: "Burundi",
    status: "BI",
    arabicName: AppStrings.burundi,
    countryCallingCode: "257",
  ),
  CountryModel(
    id: "37",
    name: "Cambodia",
    status: "KH",
    arabicName: AppStrings.cambodia,
    countryCallingCode: "855",
  ),
  CountryModel(
    id: "38",
    name: "Cameroon",
    status: "CM",
    arabicName: AppStrings.cameroon,
    countryCallingCode: "237",
  ),
  CountryModel(
    id: "39",
    name: "Canada",
    status: "CA",
    arabicName: AppStrings.canada,
    countryCallingCode: "1",
  ),
  CountryModel(
    id: "40",
    name: "Cape Verde",
    status: "CV",
    arabicName: AppStrings.capeVerde,
    countryCallingCode: "238",
  ),
  CountryModel(
    id: "41",
    name: "Cayman Islands",
    status: "KY",
    arabicName: AppStrings.caymanIslands,
    countryCallingCode: "1 345",
  ),
  CountryModel(
    id: "42",
    name: "Central African Republic",
    status: "CF",
    arabicName: AppStrings.centralAfricanRepublic,
    countryCallingCode: "236",
  ),
  CountryModel(
    id: "43",
    name: "Chad",
    status: "TD",
    arabicName: AppStrings.chad,
    countryCallingCode: "235",
  ),
  CountryModel(
    id: "44",
    name: "Chile",
    status: "CL",
    arabicName: AppStrings.chile,
    countryCallingCode: "56",
  ),
  CountryModel(
    id: "45",
    name: "China",
    status: "CN",
    arabicName: AppStrings.china,
    countryCallingCode: "86",
  ),
  CountryModel(
    id: "46",
    name: "Christmas Island",
    status: "CX",
    arabicName: AppStrings.christmasIsland,
    countryCallingCode: "61 89164",
  ),
  CountryModel(
    id: "47",
    name: "Cocos(Keeling)Islands",
    status: "CC",
    arabicName: AppStrings.autostring1,
    countryCallingCode: "61 89162",
  ),
  CountryModel(
    id: "48",
    name: "Colombia",
    status: "CO",
    arabicName: AppStrings.colombia,
    countryCallingCode: "57",
  ),
  CountryModel(
    id: "49",
    name: "Comoros",
    status: "KM",
    arabicName: AppStrings.comoros,
    countryCallingCode: "269",
  ),
  CountryModel(
    id: "50",
    name: "Congo",
    status: "CG",
    arabicName: AppStrings.congo,
    countryCallingCode: "242",
  ),
  CountryModel(
    id: "51",
    name: "Democratic Republic Of Congo",
    status: "CD",
    arabicName: AppStrings.democraticRepublicOfThe,
    countryCallingCode: "243",
  ),
  CountryModel(
    id: "52",
    name: "Cook Islands",
    status: "CK",
    arabicName: AppStrings.cookIslands,
    countryCallingCode: "682",
  ),
  CountryModel(
    id: "53",
    name: "Costa Rica",
    status: "CR",
    arabicName: AppStrings.costaRica,
    countryCallingCode: "506",
  ),
  CountryModel(
    id: "54",
    name: "Cote D'Ivoire (Ivory Coast)",
    status: "CI",
    arabicName: AppStrings.cteDivoireIvoryCoast,
    countryCallingCode: "225",
  ),
  CountryModel(
    id: "55",
    name: "Croatia (Hrvatska)",
    status: "HR",
    arabicName: AppStrings.croatiaHrvatska,
    countryCallingCode: "385",
  ),
  CountryModel(
    id: "56",
    name: "Cuba",
    status: "CU",
    arabicName: AppStrings.cuba,
    countryCallingCode: "53",
  ),
  CountryModel(
    id: "57",
    name: "Cyprus",
    status: "CY",
    arabicName: AppStrings.cyprus,
    countryCallingCode: "357",
  ),
  CountryModel(
    id: "58",
    name: "Czech Republic",
    status: "CZ",
    arabicName: AppStrings.czechRepublic,
    countryCallingCode: "420",
  ),
  CountryModel(
    id: "59",
    name: "Denmark",
    status: "DK",
    arabicName: AppStrings.denmark,
    countryCallingCode: "45",
  ),
  CountryModel(
    id: "60",
    name: "Djibouti",
    status: "DJ",
    arabicName: AppStrings.djibouti,
    countryCallingCode: "253",
  ),
  CountryModel(
    id: "61",
    name: "Dominica",
    status: "DM",
    arabicName: AppStrings.dominican,
    countryCallingCode: "1 767",
  ),
  CountryModel(
    id: "62",
    name: "Dominican Republic",
    status: "DO",
    arabicName: AppStrings.dominicanRepublic,
    countryCallingCode: "809",
  ),
  CountryModel(
    id: "63",
    name: "East Timor",
    status: "TL",
    arabicName: AppStrings.eastTimor,
    countryCallingCode: "670",
  ),
  CountryModel(
    id: "64",
    name: "Ecuador",
    status: "EC",
    arabicName: AppStrings.ecuador,
    countryCallingCode: "593",
  ),
  CountryModel(
    id: "65",
    name: "Egypt",
    status: "EG",
    arabicName: AppStrings.egypt,
    countryCallingCode: "20",
  ),
  CountryModel(
    id: "66",
    name: "El Salvador",
    status: "SV",
    arabicName: AppStrings.elSalvador,
    countryCallingCode: "503",
  ),
  CountryModel(
    id: "67",
    name: "Equatorial Guinea",
    status: "GQ",
    arabicName: AppStrings.equatorialGuinea,
    countryCallingCode: "240",
  ),
  CountryModel(
    id: "68",
    name: "Eritrea",
    status: "ER",
    arabicName: AppStrings.eritrea,
    countryCallingCode: "291",
  ),
  CountryModel(
    id: "69",
    name: "Estonia",
    status: "EE",
    arabicName: AppStrings.estonia,
    countryCallingCode: "372",
  ),
  CountryModel(
    id: "70",
    name: "Ethiopia",
    status: "ET",
    arabicName: AppStrings.ethiopia,
    countryCallingCode: "251",
  ),
  CountryModel(
    id: "71",
    name: "Falkland Islands",
    status: "FK",
    arabicName: AppStrings.falklandIslands,
    countryCallingCode: "500",
  ),
  CountryModel(
    id: "72",
    name: "Faroe Islands",
    status: "FO",
    arabicName: AppStrings.faroeIslands,
    countryCallingCode: "298",
  ),
  CountryModel(
    id: "73",
    name: "Fiji Islands",
    status: "FJ",
    arabicName: AppStrings.fijiIslands,
    countryCallingCode: "679",
  ),
  CountryModel(
    id: "74",
    name: "Finland",
    status: "FI",
    arabicName: AppStrings.finland,
    countryCallingCode: "358",
  ),
  CountryModel(
    id: "75",
    name: "France",
    status: "FR",
    arabicName: AppStrings.france,
    countryCallingCode: "33",
  ),
  CountryModel(
    id: "76",
    name: "French Guiana",
    status: "GF",
    arabicName: AppStrings.frenchGuiana,
    countryCallingCode: "594",
  ),
  CountryModel(
    id: "77",
    name: "French Polynesia",
    status: "PF",
    arabicName: AppStrings.frenchPolynesia,
    countryCallingCode: "689",
  ),
  CountryModel(
    id: "78",
    name: "French Southern Territories",
    status: "TF",
    arabicName: AppStrings.southernRegionsOfFrance,
    countryCallingCode: "262",
  ),
  CountryModel(
    id: "79",
    name: "Gabon",
    status: "GA",
    arabicName: AppStrings.gabon,
    countryCallingCode: "241",
  ),
  CountryModel(
    id: "80",
    name: "Gambia",
    status: "GM",
    arabicName: AppStrings.gambia,
    countryCallingCode: "220",
  ),
  CountryModel(
    id: "81",
    name: "Georgia",
    status: "GE",
    arabicName: AppStrings.georgia,
    countryCallingCode: "995",
  ),
  CountryModel(
    id: "82",
    name: "Germany",
    status: "DE",
    arabicName: AppStrings.germany,
    countryCallingCode: "49",
  ),
  CountryModel(
    id: "83",
    name: "Ghana",
    status: "GH",
    arabicName: AppStrings.ghana,
    countryCallingCode: "233",
  ),
  CountryModel(
    id: "84",
    name: "Gibraltar",
    status: "GI",
    arabicName: AppStrings.gibraltar,
    countryCallingCode: "350",
  ),
  CountryModel(
    id: "85",
    name: "Gibraltar",
    status: "GI",
    arabicName: AppStrings.gibraltar,
    countryCallingCode: "350",
  ),
  CountryModel(
    id: "86",
    name: "Greenland",
    status: "GL",
    arabicName: AppStrings.greenland,
    countryCallingCode: "299",
  ),
  CountryModel(
    id: "87",
    name: "Grenada",
    status: "GD",
    arabicName: AppStrings.grenada,
    countryCallingCode: "473",
  ),
  CountryModel(
    id: "88",
    name: "Guadeloupe",
    status: "GP",
    arabicName: AppStrings.guadeloupe,
    countryCallingCode: "590",
  ),
  CountryModel(
    id: "89",
    name: "Guam",
    status: "GU",
    arabicName: AppStrings.guam,
    countryCallingCode: "1 671",
  ),
  CountryModel(
    id: "90",
    name: "Guatemala",
    status: "GT",
    arabicName: AppStrings.guatemala,
    countryCallingCode: "502",
  ),
  CountryModel(
    id: "91",
    name: "Guernsey and Alderney",
    status: "GG",
    arabicName: AppStrings.alderney,
    countryCallingCode: " 44 1481",
  ),
  CountryModel(
    id: "92",
    name: "Guinea",
    status: "GN",
    arabicName: AppStrings.guinea,
    countryCallingCode: "675",
  ),
  CountryModel(
    id: "93",
    name: "Guinea-Bissau",
    status: "GW",
    arabicName: AppStrings.guineaBissau,
    countryCallingCode: "245",
  ),
  CountryModel(
    id: "94",
    name: "Guyana",
    status: "GY",
    arabicName: AppStrings.guyana,
    countryCallingCode: "592",
  ),
  CountryModel(
    id: "95",
    name: "Haiti",
    status: "HT",
    arabicName: AppStrings.haiti,
    countryCallingCode: "509",
  ),
  CountryModel(
    id: "96",
    name: "Heard Island and McDonald Islands",
    status: "HN",
    arabicName: AppStrings.heardIslandAndMcdonald,
    countryCallingCode: "504",
  ),
  CountryModel(
    id: "97",
    name: "Honduras",
    status: "HN",
    arabicName: AppStrings.honduras,
    countryCallingCode: "504",
  ),
  CountryModel(
    id: "98",
    name: "Hong Kong S.A.R.",
    status: "HK",
    arabicName: AppStrings.hongKongSpecialAdministrative,
    countryCallingCode: "582",
  ),
  CountryModel(
    id: "99",
    name: "Hungary",
    status: "HU",
    arabicName: AppStrings.hungary,
    countryCallingCode: "36",
  ),
  CountryModel(
    id: "100",
    name: "Iceland",
    status: "IS",
    arabicName: AppStrings.iceland,
    countryCallingCode: "354",
  ),
  CountryModel(
    id: "101",
    name: "India",
    status: "IN",
    arabicName: AppStrings.india,
    countryCallingCode: "91",
  ),
  CountryModel(
    id: "102",
    name: "Indonesia",
    status: "ID",
    arabicName: AppStrings.indonesia,
    countryCallingCode: "62",
  ),
  CountryModel(
    id: "103",
    name: "Iran",
    status: "IR",
    arabicName: AppStrings.iran,
    countryCallingCode: "98",
  ),
  CountryModel(
    id: "104",
    name: "Iraq",
    status: "IQ",
    arabicName: AppStrings.iraq,
    countryCallingCode: "964",
  ),
  CountryModel(
    id: "105",
    name: "Ireland",
    status: "IE",
    arabicName: AppStrings.ireland,
    countryCallingCode: "353",
  ),
  CountryModel(
    id: "106",
    name: "Ireland",
    status: "IE",
    arabicName: AppStrings.ireland,
    countryCallingCode: "353",
  ),
  CountryModel(
    id: "107",
    name: "Italy",
    status: "IT",
    arabicName: AppStrings.italy,
    countryCallingCode: "39",
  ),
  CountryModel(
    id: "108",
    name: "Jamaica",
    status: "JM",
    arabicName: AppStrings.jamaica,
    countryCallingCode: "1 876",
  ),
  CountryModel(
    id: "109",
    name: "Japan",
    status: "JP",
    arabicName: AppStrings.japan,
    countryCallingCode: "81",
  ),
  CountryModel(
    id: "110",
    name: "Jersey",
    status: "JE",
    arabicName: AppStrings.jersey,
    countryCallingCode: "44 1534",
  ),
  CountryModel(
    id: "111",
    name: "Jordan",
    status: "JO",
    arabicName: AppStrings.jordan,
    countryCallingCode: "962",
  ),
  CountryModel(
    id: "112",
    name: "Kazakhstan",
    status: "KZ",
    arabicName: AppStrings.kazakhstan,
    countryCallingCode: "997",
  ),
  CountryModel(
    id: "113",
    name: "Kenya",
    status: "KE",
    arabicName: AppStrings.kenya,
    countryCallingCode: "254",
  ),
  CountryModel(
    id: "114",
    name: "Kiribati",
    status: "KI",
    arabicName: AppStrings.kiribati,
    countryCallingCode: "686",
  ),
  CountryModel(
    id: "115",
    name: "Korea North",
    status: "KR",
    arabicName: AppStrings.northKorea,
    countryCallingCode: "850",
  ),
  CountryModel(
    id: "116",
    name: "Korea South",
    status: "PK",
    arabicName: AppStrings.southKorea,
    countryCallingCode: "82",
  ),
  CountryModel(
    id: "117",
    name: "Kuwait",
    status: "KW",
    arabicName: AppStrings.kuwait,
    countryCallingCode: "965",
  ),
  CountryModel(
    id: "118",
    name: "Kyrgyzstan",
    status: "KG",
    arabicName: AppStrings.kyrgyzstan,
    countryCallingCode: "996",
  ),
  CountryModel(
    id: "119",
    name: "Laos",
    status: "LA",
    arabicName: AppStrings.laos,
    countryCallingCode: "856",
  ),
  CountryModel(
    id: "120",
    name: "Latvia",
    status: "LV",
    arabicName: AppStrings.latvia,
    countryCallingCode: "371",
  ),
  CountryModel(
    id: "121",
    name: "Lebanon",
    status: "LB",
    arabicName: AppStrings.lebanon,
    countryCallingCode: "961",
  ),
  CountryModel(
    id: "122",
    name: "Lesotho",
    status: "LS",
    arabicName: AppStrings.lesotho,
    countryCallingCode: "266",
  ),
  CountryModel(
    id: "123",
    name: "Liberia",
    status: "LR",
    arabicName: AppStrings.liberia,
    countryCallingCode: "231",
  ),
  CountryModel(
    id: "124",
    name: "Libya",
    status: "LY",
    arabicName: AppStrings.libya,
    countryCallingCode: "218",
  ),
  CountryModel(
    id: "125",
    name: "Liechtenstein",
    status: "LI",
    arabicName: AppStrings.liechtenstein,
    countryCallingCode: "423",
  ),
  CountryModel(
    id: "126",
    name: "Lithuania",
    status: "LT",
    arabicName: AppStrings.lithuania,
    countryCallingCode: "370",
  ),
  CountryModel(
    id: "127",
    name: "Luxembourg",
    status: "LU",
    arabicName: AppStrings.luxembourg,
    countryCallingCode: "352",
  ),
  CountryModel(
    id: "128",
    name: "Macau S.A.R.",
    status: "MO",
    arabicName: AppStrings.macauSpecialAdministrativeRegions,
    countryCallingCode: "853",
  ),
  CountryModel(
    id: "129",
    name: "Macedonia",
    status: "MK",
    arabicName: AppStrings.macedonia,
    countryCallingCode: "389",
  ),
  CountryModel(
    id: "130",
    name: "Madagascar",
    status: "MG",
    arabicName: AppStrings.madagascar,
    countryCallingCode: "261",
  ),
  CountryModel(
    id: "131",
    name: "Malawi",
    status: "MW",
    arabicName: AppStrings.malawi,
    countryCallingCode: "265",
  ),
  CountryModel(
    id: "132",
    name: "Malaysia",
    status: "MY",
    arabicName: AppStrings.malaysia,
    countryCallingCode: "60",
  ),
  CountryModel(
    id: "133",
    name: "Maldives",
    status: "MV",
    arabicName: AppStrings.maldives,
    countryCallingCode: "960",
  ),
  CountryModel(
    id: "134",
    name: "Mali",
    status: "ML",
    arabicName: AppStrings.financial,
    countryCallingCode: "223",
  ),
  CountryModel(
    id: "135",
    name: "Malta",
    status: "MT",
    arabicName: AppStrings.malta,
    countryCallingCode: "356",
  ),
  CountryModel(
    id: "136",
    name: "Man (Isle of)",
    status: "IM",
    arabicName: AppStrings.manIsland,
    countryCallingCode: "44",
  ),
  CountryModel(
    id: "137",
    name: "Marshall Islands",
    status: "MH",
    arabicName: AppStrings.marshallIslands,
    countryCallingCode: "692",
  ),
  CountryModel(
    id: "138",
    name: "Martinique",
    status: "MQ",
    arabicName: AppStrings.martinique,
    countryCallingCode: "596",
  ),
  CountryModel(
    id: "139",
    name: "Mauritania",
    status: "MR",
    arabicName: AppStrings.mauritania,
    countryCallingCode: "222",
  ),
  CountryModel(
    id: "140",
    name: "Mauritius",
    status: "MU",
    arabicName: AppStrings.mauritius,
    countryCallingCode: "230",
  ),
  CountryModel(
    id: "141",
    name: "Mayotte",
    status: "YT",
    arabicName: AppStrings.mayotte,
    countryCallingCode: "262",
  ),
  CountryModel(
    id: "142",
    name: "Mexico",
    status: "MX",
    arabicName: AppStrings.mexico,
    countryCallingCode: "52",
  ),
  CountryModel(
    id: "143",
    name: "Micronesia",
    status: "FM",
    arabicName: AppStrings.micronesia,
    countryCallingCode: "691",
  ),
  CountryModel(
    id: "144",
    name: "Moldova",
    status: "MD",
    arabicName: AppStrings.moldova,
    countryCallingCode: "373",
  ),
  CountryModel(
    id: "145",
    name: "Monaco",
    status: "MC",
    arabicName: AppStrings.monaco,
    countryCallingCode: "377",
  ),
  CountryModel(
    id: "146",
    name: "Mongolia",
    status: "MN",
    arabicName: AppStrings.mongolia,
    countryCallingCode: "976",
  ),
  CountryModel(
    id: "147",
    name: "Montenegro",
    status: "ME",
    arabicName: AppStrings.montenegro,
    countryCallingCode: "382",
  ),
  CountryModel(
    id: "148",
    name: "Montserrat",
    status: "MS",
    arabicName: AppStrings.montserrat,
    countryCallingCode: "1 664",
  ),
  CountryModel(
    id: "149",
    name: "Morocco",
    status: "MA",
    arabicName: AppStrings.morocco,
    countryCallingCode: "212",
  ),
  CountryModel(
    id: "150",
    name: "Mozambique",
    status: "MZ",
    arabicName: AppStrings.mozambique,
    countryCallingCode: "258",
  ),
  CountryModel(
    id: "151",
    name: "Myanmar",
    status: "MM",
    arabicName: AppStrings.myanmar,
    countryCallingCode: "95",
  ),
  CountryModel(
    id: "152",
    name: "Namibia",
    status: "NA",
    arabicName: AppStrings.namibia,
    countryCallingCode: "264",
  ),
  CountryModel(
    id: "153",
    name: "Nauru",
    status: "NR",
    arabicName: AppStrings.nauru,
    countryCallingCode: "674",
  ),
  CountryModel(
    id: "154",
    name: "Nepal",
    status: "NP",
    arabicName: AppStrings.nepal,
    countryCallingCode: "977",
  ),
  CountryModel(
    id: "155",
    name: "Bonaire, Sint Eustatius and Saba",
    status: "NL",
    arabicName: AppStrings.dutchCaribbeanIslands,
    countryCallingCode: "599",
  ),
  CountryModel(
    id: "156",
    name: "Netherlands ",
    status: "NL",
    arabicName: AppStrings.holland,
    countryCallingCode: "31",
  ),
  CountryModel(
    id: "157",
    name: "New Caledonia",
    status: "NC",
    arabicName: AppStrings.newCaledonia,
    countryCallingCode: "687",
  ),
  CountryModel(
    id: "158",
    name: "New Zealand",
    status: "NZ",
    arabicName: AppStrings.newZealand,
    countryCallingCode: "64",
  ),
  CountryModel(
    id: "159",
    name: "Nicaragua",
    status: "NI",
    arabicName: AppStrings.nicaragua,
    countryCallingCode: "505",
  ),
  CountryModel(
    id: "160",
    name: "Niger",
    status: "NE",
    arabicName: AppStrings.niger,
    countryCallingCode: "227",
  ),
  CountryModel(
    id: "161",
    name: "Nigeria",
    status: "NG",
    arabicName: AppStrings.nigeria,
    countryCallingCode: "234",
  ),
  CountryModel(
    id: "162",
    name: "Niue",
    status: "NI",
    arabicName: AppStrings.niue,
    countryCallingCode: "683",
  ),
  CountryModel(
    id: "163",
    name: "Norfolk Island",
    status: "NF",
    arabicName: AppStrings.norfolkIsland,
    countryCallingCode: "672 3",
  ),
  CountryModel(
    id: "164",
    name: "Northern Mariana Islands",
    status: "MP",
    arabicName: AppStrings.northernMarianaIslands,
    countryCallingCode: "1 670",
  ),
  CountryModel(
    id: "165",
    name: "Norway",
    status: "NO",
    arabicName: AppStrings.norway,
    countryCallingCode: "47",
  ),
  CountryModel(
    id: "166",
    name: "Oman",
    status: "OM",
    arabicName: AppStrings.oman,
    countryCallingCode: "968",
  ),
  CountryModel(
    id: "167",
    name: "Pakistan",
    status: "PK",
    arabicName: AppStrings.pakistan,
    countryCallingCode: "92",
  ),
  CountryModel(
    id: "168",
    name: "Palau",
    status: "PW",
    arabicName: AppStrings.palau,
    countryCallingCode: "680",
  ),
  CountryModel(
    id: "169",
    name: "Palestinian Territory Occupied",
    status: "PS",
    arabicName: AppStrings.occupiedPalestinianTerritories,
    countryCallingCode: "972",
  ),
  CountryModel(
    id: "170",
    name: "Panama",
    status: "PA",
    arabicName: AppStrings.panama,
    countryCallingCode: "507",
  ),
  CountryModel(
    id: "171",
    name: "Papua new Guinea",
    status: "PG",
    arabicName: AppStrings.papuaNewGuinea,
    countryCallingCode: "675",
  ),
  CountryModel(
    id: "172",
    name: "Paraguay",
    status: "PY",
    arabicName: AppStrings.paraguay,
    countryCallingCode: "595",
  ),
  CountryModel(
    id: "173",
    name: "Peru",
    status: "PE",
    arabicName: AppStrings.peru,
    countryCallingCode: "51",
  ),
  CountryModel(
    id: "174",
    name: "Philippines",
    status: "PH",
    arabicName: AppStrings.thePhilippines,
    countryCallingCode: "63",
  ),
  CountryModel(
    id: "175",
    name: "Pitcairn Island",
    status: "PN",
    arabicName: AppStrings.pitcairnIsland,
    countryCallingCode: "64",
  ),
  CountryModel(
    id: "176",
    name: "Poland",
    status: "PL",
    arabicName: AppStrings.poland,
    countryCallingCode: "48",
  ),
  CountryModel(
    id: "177",
    name: "Portugal",
    status: "PT",
    arabicName: AppStrings.portugal,
    countryCallingCode: "351",
  ),
  CountryModel(
    id: "178",
    name: "Puerto Rico",
    status: "PR",
    arabicName: AppStrings.puertoRico,
    countryCallingCode: "787",
  ),
  CountryModel(
    id: "179",
    name: "Qatar",
    status: "QA",
    arabicName: AppStrings.qatar,
    countryCallingCode: "974",
  ),
  CountryModel(
    id: "180",
    name: "Reunion",
    status: "RE",
    arabicName: AppStrings.reunion,
    countryCallingCode: "262",
  ),
  CountryModel(
    id: "181",
    name: "Romania",
    status: "RO",
    arabicName: AppStrings.romania,
    countryCallingCode: "40",
  ),
  CountryModel(
    id: "182",
    name: "Russia",
    status: "RU",
    arabicName: AppStrings.russia,
    countryCallingCode: "7",
  ),
  CountryModel(
    id: "183",
    name: "Rwanda",
    status: "RW",
    arabicName: AppStrings.rwanda,
    countryCallingCode: "250",
  ),
  CountryModel(
    id: "184",
    name: "Saint Helena",
    status: "SH",
    arabicName: AppStrings.saintHelena,
    countryCallingCode: "290",
  ),
  CountryModel(
    id: "185",
    name: "Saint Kitts And Nevis",
    status: "KN",
    arabicName: AppStrings.saintKittsAndNevis,
    countryCallingCode: "1 869",
  ),
  CountryModel(
    id: "186",
    name: "Saint Lucia",
    status: "LC",
    arabicName: AppStrings.saintLucia,
    countryCallingCode: "758",
  ),
  CountryModel(
    id: "187",
    name: "Saint Pierre and Miquelon",
    status: "PM",
    arabicName: AppStrings.stPierreAndMicolon,
    countryCallingCode: "508",
  ),
  CountryModel(
    id: "188",
    name: "Saint Vincent And The Grenadines",
    status: "VC",
    arabicName: AppStrings.saintVincentAndThe,
    countryCallingCode: "1 784",
  ),
  CountryModel(
    id: "189",
    name: "Saint Barthelemy",
    status: "BL",
    arabicName: AppStrings.saintBarthelemy,
    countryCallingCode: "590",
  ),
  CountryModel(
    id: "190",
    name: "Saint Martin (French)",
    status: "MF",
    arabicName: AppStrings.saintMartinFrenchPart,
    countryCallingCode: "590",
  ),
  CountryModel(
    id: "191",
    name: "Samoa",
    status: "WS",
    arabicName: AppStrings.samoa,
    countryCallingCode: "685",
  ),
  CountryModel(
    id: "192",
    name: "San Marino",
    status: "SM",
    arabicName: AppStrings.sanMarino,
    countryCallingCode: "378",
  ),
  CountryModel(
    id: "193",
    name: "Sao Tome and Principe",
    status: "ST",
    arabicName: AppStrings.saoTomeAndPrincipe,
    countryCallingCode: "239",
  ),
  CountryModel(
    id: "194",
    name: "Saudi Arabia",
    status: "SA",
    arabicName: AppStrings.kingdomOfSaudiArabia,
    countryCallingCode: "966",
  ),
  CountryModel(
    id: "195",
    name: "Senegal",
    status: "SN",
    arabicName: AppStrings.senegal,
    countryCallingCode: "221",
  ),
  CountryModel(
    id: "196",
    name: "Serbia",
    status: "RS",
    arabicName: AppStrings.serbia,
    countryCallingCode: "381",
  ),
  CountryModel(
    id: "197",
    name: "Seychelles",
    status: "SC",
    arabicName: AppStrings.seychelles,
    countryCallingCode: "248",
  ),
  CountryModel(
    id: "198",
    name: "Sierra Leone",
    status: "SL",
    arabicName: AppStrings.sierraLeone,
    countryCallingCode: "232",
  ),
  CountryModel(
    id: "199",
    name: "Singapore",
    status: "SG",
    arabicName: AppStrings.singapore,
    countryCallingCode: "65",
  ),
  CountryModel(
    id: "200",
    name: "Slovakia",
    status: "SK",
    arabicName: AppStrings.slovakia,
    countryCallingCode: "421",
  ),
  CountryModel(
    id: "201",
    name: "Slovenia",
    status: "SI",
    arabicName: AppStrings.slovenia,
    countryCallingCode: "386",
  ),
  CountryModel(
    id: "202",
    name: "Solomon Islands",
    status: "SB",
    arabicName: AppStrings.solomonIslands,
    countryCallingCode: "677",
  ),
  CountryModel(
    id: "203",
    name: "Somalia",
    status: "SO",
    arabicName: AppStrings.somalia,
    countryCallingCode: "252",
  ),
  CountryModel(
    id: "204",
    name: "South Africa",
    status: "ZA",
    arabicName: AppStrings.southAfrica,
    countryCallingCode: "27",
  ),
  CountryModel(
    id: "205",
    name: "South Georgia",
    status: "GB",
    arabicName: AppStrings.southGeorgia,
    countryCallingCode: "500",
  ),
  CountryModel(
    id: "206",
    name: "South Sudan",
    status: "SS",
    arabicName: AppStrings.southSudan,
    countryCallingCode: "211",
  ),
  CountryModel(
    id: "207",
    name: "Spain",
    status: "ES",
    arabicName: AppStrings.spain,
    countryCallingCode: "34",
  ),
  CountryModel(
    id: "208",
    name: "Sri Lanka",
    status: "LK",
    arabicName: AppStrings.sriLanka,
    countryCallingCode: "94",
  ),
  CountryModel(
    id: "209",
    name: "Sudan",
    status: "SD",
    arabicName: AppStrings.sudan,
    countryCallingCode: "249",
  ),
  CountryModel(
    id: "210",
    name: "Suriname",
    status: "SR",
    arabicName: AppStrings.suriname,
    countryCallingCode: "597",
  ),
  CountryModel(
    id: "211",
    name: "Svalbard And Jan Mayen Islands",
    status: "SJ",
    arabicName: AppStrings.svalbardAndJanMayen,
    countryCallingCode: "47 79",
  ),
  CountryModel(
    id: "212",
    name: "Swaziland",
    status: "SZ",
    arabicName: AppStrings.swaziland,
    countryCallingCode: "268",
  ),
  CountryModel(
    id: "213",
    name: "Sweden",
    status: "SE",
    arabicName: AppStrings.sweden,
    countryCallingCode: "46",
  ),
  CountryModel(
    id: "214",
    name: "Switzerland",
    status: "CH",
    arabicName: AppStrings.switzerland,
    countryCallingCode: "41",
  ),
  CountryModel(
    id: "215",
    name: "Syria",
    status: "SY",
    arabicName: AppStrings.syria,
    countryCallingCode: "963",
  ),
  CountryModel(
    id: "216",
    name: "Taiwan",
    status: "TW",
    arabicName: AppStrings.taiwan,
    countryCallingCode: "886",
  ),
  CountryModel(
    id: "217",
    name: "Tajikistan",
    status: "TJ",
    arabicName: AppStrings.tajikistan,
    countryCallingCode: "992",
  ),
  CountryModel(
    id: "218",
    name: "Tanzania",
    status: "TZ",
    arabicName: AppStrings.tanzania,
    countryCallingCode: "259",
  ),
  CountryModel(
    id: "219",
    name: "Thailand",
    status: "TH",
    arabicName: AppStrings.thailand,
    countryCallingCode: "66",
  ),
  CountryModel(
    id: "220",
    name: "Togo",
    status: "TG",
    arabicName: AppStrings.togo,
    countryCallingCode: "228",
  ),
  CountryModel(
    id: "221",
    name: "Tokelau",
    status: "TK",
    arabicName: AppStrings.tokelau,
    countryCallingCode: "690",
  ),
  CountryModel(
    id: "222",
    name: "Tonga",
    status: "TO",
    arabicName: AppStrings.tonga,
    countryCallingCode: "676",
  ),
  CountryModel(
    id: "223",
    name: "Trinidad And Tobago",
    status: "TT",
    arabicName: AppStrings.trinidadAndTobago,
    countryCallingCode: "1 868",
  ),
  CountryModel(
    id: "224",
    name: "Tunisia",
    status: "TN",
    arabicName: AppStrings.tunisia,
    countryCallingCode: "216",
  ),
  CountryModel(
    id: "225",
    name: "Turkey",
    status: "TR",
    arabicName: AppStrings.trkiye,
    countryCallingCode: "90",
  ),
  CountryModel(
    id: "226",
    name: "Turkmenistan",
    status: "TK",
    arabicName: AppStrings.turkmenistan,
    countryCallingCode: "993",
  ),
  CountryModel(
    id: "227",
    name: "Turks And Caicos Islands",
    status: "TC",
    arabicName: AppStrings.turksAndCaicosIslands,
    countryCallingCode: "1 649",
  ),
  CountryModel(
    id: "228",
    name: "Tuvalu",
    status: "TV",
    arabicName: AppStrings.tuvalu,
    countryCallingCode: "688",
  ),
  CountryModel(
    id: "229",
    name: "Uganda",
    status: "UG",
    arabicName: AppStrings.uganda,
    countryCallingCode: "256",
  ),
  CountryModel(
    id: "230",
    name: "Ukraine",
    status: "UA",
    arabicName: AppStrings.ukraine,
    countryCallingCode: "380",
  ),
  CountryModel(
    id: "231",
    name: "United Arab Emirates",
    status: "AE",
    arabicName: AppStrings.unitedArabEmirates,
    countryCallingCode: "971",
  ),
  CountryModel(
    id: "232",
    name: "United Kingdom",
    status: "GB",
    arabicName: AppStrings.uk,
    countryCallingCode: "44",
  ),
  CountryModel(
    id: "233",
    name: "United States",
    status: "US",
    arabicName: AppStrings.us,
    countryCallingCode: "1",
  ),
  CountryModel(
    id: "234",
    name: "United States Minor Outlying Islands",
    status: "UM",
    arabicName: AppStrings.outlyingIslandsOfThe,
    countryCallingCode: "581",
  ),
  CountryModel(
    id: "235",
    name: "Uruguay",
    status: "UY",
    arabicName: AppStrings.uruguay,
    countryCallingCode: "598",
  ),
  CountryModel(
    id: "236",
    name: "Uzbekistan",
    status: "UZ",
    arabicName: AppStrings.uzbekistan,
    countryCallingCode: "998",
  ),
  CountryModel(
    id: "237",
    name: "Vanuatu",
    status: "VU",
    arabicName: AppStrings.vanuatu,
    countryCallingCode: "678",
  ),
  CountryModel(
    id: "238",
    name: "Vatican City State (Holy See)",
    status: "VA",
    arabicName: AppStrings.vatican,
    countryCallingCode: "379",
  ),
  CountryModel(
    id: "239",
    name: "Venezuela",
    status: "VE",
    arabicName: AppStrings.venezuela,
    countryCallingCode: "58",
  ),
  CountryModel(
    id: "240",
    name: "Vietnam",
    status: "VN",
    arabicName: AppStrings.vietnam,
    countryCallingCode: "84",
  ),
  CountryModel(
    id: "241",
    name: "Virgin Islands (British)",
    status: "VG",
    arabicName: AppStrings.britishVirginIslands,
    countryCallingCode: "284",
  ),
  CountryModel(
    id: "242",
    name: "Virgin Islands (US)",
    status: "VI",
    arabicName: AppStrings.usVirginIslands,
    countryCallingCode: "340",
  ),
  CountryModel(
    id: "243",
    name: "Wallis And Futuna",
    status: "WF",
    arabicName: AppStrings.wallisAndFutuna,
    countryCallingCode: "681",
  ),
  CountryModel(
    id: "244",
    name: "Western Sahara",
    status: "EH",
    arabicName: AppStrings.westernSahara,
    countryCallingCode: "212",
  ),
  CountryModel(
    id: "245",
    name: "Yemen",
    status: "YE",
    arabicName: AppStrings.yemen,
    countryCallingCode: "967",
  ),
  CountryModel(
    id: "246",
    name: "Zambia",
    status: "ZM",
    arabicName: AppStrings.zambia,
    countryCallingCode: "260",
  ),
  CountryModel(
    id: "247",
    name: "Zimbabwe",
    status: "ZW",
    arabicName: AppStrings.zimbabwe,
    countryCallingCode: "263",
  ),
  CountryModel(
    id: "248",
    name: "Kosovo",
    status: "XK",
    arabicName: AppStrings.kosovo,
    countryCallingCode: "383",
  ),
  CountryModel(
    id: "249",
    name: "Curaçao",
    status: "CW",
    arabicName: AppStrings.curacao,
    countryCallingCode: "599 9",
  ),
  CountryModel(
    id: "250",
    name: "Sint Maarten (Dutch part)",
    status: "SX",
    arabicName: AppStrings.sintMaartenDutchPart,
    countryCallingCode: "383",
  ),
];
